const data = [
  {
    name: "Luthfi Rahmani",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 2,
    name: "Diki Ari Febriyanto",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 3,
    name: "Rifki Ridha",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 4,
    name: "Muhamad Anval Hafitansyah",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 5,
    name: "Rizky Maulana Rajabi",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 6,
    name: "Pandu Wibisana",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 7,
    name: "Ananda Destyani Putri",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 8,
    name: "Muhammad Fadhillah",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 9,
    name: "Luthfiandy Ramadhana",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
  {
    id: 10,
    name: "Ridwan",
    program: "Aigen Bootcamp Fullstack Javascript",
    Date: "8 Mei - 8 Juli",
    Status: "Lulus",
    Certificate: "Valid",
  },
];

export default data;
